### ISSUE TITLE
New version

### ISSUE THREAD

**Issue by BlueHotDog** [bugsnag-elixir/bugsnag-elixir#109]
Any chance to release a new version with all the fixes?

**Comment by BlueHotDog** [comment]
ping?
i really need the http adapter override fix.. and running on top of a commit sucks

**Comment by BlueHotDog** [comment]
hey guys, is this project under active development?

**Comment by nathan-cruz77** [comment]
Hey @BlueHotDog, I'm not a maintainer but I noticed a new version (3.0.0) was released a few days ago: https://hex.pm/packages/bugsnag. Changelogs can be found [here](https://github.com/bugsnag-elixir/bugsnag-elixir/blob/master/CHANGELOG.md).

**Comment by nirev** [comment]
hey @BlueHotDog @nathan-cruz77 sorry about this. 
While I had access to code pushing, I did not have access to hex.pm yet. 
the original maintainer has given me access to hex.pm now, so you should expect more timely publishes now.
