### ISSUE TITLE
Bugsnag stoped sending information on OTP23

### ISSUE THREAD

**Issue by prabello** [bugsnag-elixir/bugsnag-elixir#96]
Bugsnag is using HTTPoison to send information to `https://notify.bugsnag.com`, after the upgrade of OTP to v23 this is causing some SSL issues, better described here: https://github.com/benoitc/hackney/pull/619

To solve this on our projects we are using the most recent hackney version `{:hackney, "~> 1.16"},`

I believe this is something to be dealt on HTTPoison, but since Bugsnag silently stopped sending information, might be wort to consider

HTTPoison issue: https://github.com/edgurgel/httpoison/issues/411

**Comment by BlueHotDog** [comment]
Second that. i also tried the master branch as it should allow setting up your own client to send but it has some issues(the request.url isnt setup correctly but points to the url of my app for some reason).

Are you looking for PRs to fix this?

**Comment by nirev** [comment]
@BlueHotDog I would very much appreciate a PR. the original issue seems to be fixed as of the latest httpoison version (which bumped hackney requirement), but if you could provide a PR fixing the `request.url` or even a failing test case, that would be amazing.

**Comment by BlueHotDog** [comment]
Actually, after taking a sober look into this, it actually works as expected. or at least, it does report the error as expected but the stacktrace isnt shown as needed. I think this issue can be resolved(and pushed a new version to Hex) and maybe there's a followup issue that i can open regarding the stacktrace.

**Comment by nirev** [comment]
That sounds good. I'm going to close this one 🙇 
Thank you!
