### ISSUE TITLE
Customize errorClass

### ISSUE THREAD

**Issue by sb8244** [bugsnag-elixir/bugsnag-elixir#97]
I often use Bugsnag to log caught exceptions / edge cases that I want to know about. If I use `Bugsnag.report("something")`, the errorClass appears as "Elixir.ErlangError" because of the error normalization.

Is there a way to easily have this appear as a custom named exception? I know it's possible to do with a custom module like:

```
  defmodule Custom.ValidationErrors do
    # tricks normalize into thinking it's an exception
    defstruct errs: [], __exception__: true

    def new(errs) do
      %__MODULE__{errs: errs}
    end

    def message(errs) do
      inspect(errs)
    end
```

But I'm hoping there's a lighter way

**Comment by nathan-cruz77** [comment]
Hey @sb8244, I just opened a [PR](https://github.com/bugsnag-elixir/bugsnag-elixir/pull/108) adding an option to customize the error class when reporting.

Usage looks like:
```elixir
Bugsnag.report("something", error_class: RuntimeError)
```

Let me know if you have any feedback.

Hope that's what you were looking for :smiley:.
